print("How old are you?", end=' ')
age = input()
print("How tall are you (in cm's)?", end=' ')
height = input()
print("How much do you weigh (in Kg)?", end=' ')
weight = input()
print(f"So, you're {age} years old, {height}cm tall and {weight}Kg heavy.")
